name: CI
on: [push]
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Restore Dependencies
        uses: actions/cache@v2
        id: node-cache
        with:
          # https://dev.to/mpocock1/how-to-cache-nodemodules-in-github-actions-with-yarn-24eh
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install Dependencies
        run: yarn install
      - name: Build Project
        run: yarn run build
      - name: Run Tests
        run: yarn run test
